title: "My story to become better than the average" 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
avatar: https://pbs.twimg.com/profile_images/82772867/624570022_d79b897fee_400x400.jpg
